# Copyright (C) 2026 Advanced Micro Devices, Inc. All rights reserved.

---
- name: Reload udev rules
  ansible.builtin.command:
    argv:
      - udevadm
      - control
      - --reload-rules
  when: auplc_rootfs_path | length == 0

- name: Trigger udev rules
  ansible.builtin.command:
    argv:
      - udevadm
      - trigger
  when: auplc_rootfs_path | length == 0
