[workspace]
authors = ["noamonti748"]
channels = ["conda-forge"]
name = "rocm-warp-mujoco"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
glew = "*"
libegl-devel = ">=1.7.0,<2"
libgl-devel = ">=1.7.0,<2"
libglx-devel = ">=1.7.0,<2"
mesalib = "<25.1.0"
